### ISSUE TITLE
[Glide] Targets are never cleared

### ISSUE THREAD

**Issue by guillaume-tgl** [skydoves/landscapist#265] opened 2023-04-25 12:40 UTC
**Please complete the following information:**
- Library Version v2.1.9
- Affected Device(s) All
 
**Describe the Bug:**

I have a LazyColumn where an image is loaded with Glide in each item. And I've noticed that the memory cache is never used in that case because a new `FlowCustomTarget` is used for each new `item` and it's never cleared, preventing the resource from being added to the memory cache.
Also the target is not cleared when the flow is closed and there's this comment in the `awaitClose` block:
```
// intentionally do not clear using the Glide.clear for recycling internal bitmaps.
```

**Expected Behavior:**

I expect the resources to be cached in memory when they are not visible anymore so that they can be later retrieved.

**Comment by skydoves** [comment] 2023-04-25 13:50
Hey @guillaume-tgl, this is a little bit more tricky than expected solution because Glide is not allowed to use a recycled bitmap. You can easily reproduce this issue by changing the comment with `Glide.clear` function with LazyColumn and LazyRow in the demo project. 

Do you use a `key` parameter in `LazyColumn` for identifying each item?

**Comment by skydoves** [comment] 2023-05-01 13:04
Hey @guillaume-tgl, I was thinking of this a bit, and I tweaked it a bit to clear the target out of the scope. It's available in the snapshot right now, and it will be included in the next release.

**Closed** 2023-05-01 13:29 UTC
